export default {
  APP_INITIALIZED_SUCCESS: 'APP_INITIALIZED_SUCCESS',
  FETCH_SUMMONER_START: 'FETCH_SUMMONER_START',
  FETCH_SUMMONER_SUCCESS: 'FETCH_SUMMONER_SUCCESS',
  FETCH_SUMMONER_FAILURE: 'FETCH_SUMMONER_FAILURE',
};
